### ISSUE TITLE
Having trouble with multi-folder workspace

### ISSUE THREAD

**Issue by westy** [spmeesseman/vscode-extjs#3]
Hi,

I am currently trialing a move to VSCode from Sublime, and found your plugin.
Seems great from what I can see, although I am having a few teething issues.

Our source is spread over several applications and packages.
I have built a VSCode workspace that contains all the workspace directories, but I only seem to get ExtJS indexing on the workspace in the same directory as the .code-workspace file.

I also seem to get no help for Ext libraries. I have tried settings the directory in settings, to the root of Ext 6.7.0 (yeah, I know!), but I don't think it's indexing it.

Any pointers please?

Cheers,
Westy

**Comment by spmeesseman** [comment]
i noticed this the other day, very strange bug going on, but ill find it and fix soon enough

**Comment by westy** [comment]
Would appreciate some guidance on how to use this across multiple repos too, since have not got anything working as yet!

So you have multiple apps and packages across different folders in your workspace, or is your workspace just the sencha workspace folder?

Cheers
