### ISSUE TITLE
add framework version in settings

### ISSUE THREAD

**Issue by aurban6** [spmeesseman/vscode-extjs#6]
Pleas add framework version in settings for generate help link or read from workspace.json frameworks.ext.version

![image](https://user-images.githubusercontent.com/10771625/152160663-ba2cc83c-7c24-4b0f-a230-02f19a934f58.png)

**Comment by spmeesseman** [comment]
you can add docs for any namespace by adding to your settings json:

```
docURL: {
    "Ext": "https://docs.sencha.com/extjs/7.4.0"
}
```

ill add it to the readme when i have a chance
